language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip3 install pycodestyle

script:
  - python3 -m unittest -v tests/*.py

jobs:
  include:
    - stage: codestyle
      script: git diff master..HEAD | pycodestyle --diff

notifications:
  email: false
